import { type NextPage } from "next";
import { SignIn, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Head from "next/head";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import Link from "next/link";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Temoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  );
};

export default Home;
